box_map <- function(...) {
  data.frame(
    id = c("unemployment_rate",
           "unemployed",
           "employment_total",
           "participation_rate", 
           "employment_ft",
           "employment_pt",
           "underemployed",
           "underutilised",
           "underemployment_rate",
           "underutilisation_rate", 
           "hours_worked_total", 
           "labour_force_total"),
    indicator = c("Unemployment rate",
                  "Unemployed total", 
                  "Employed total", 
                  "Participation rate",
                  "Employed full-time", 
                  "Employed part-time", 
                  "Underemployed total",
                  "Underutilised total",
                  "Underemployment rate (proportion of labour force)",
                  "Underutilisation rate",
                  "Monthly hours worked in all jobs",
                  "Labour force total"),
    reverse = c(TRUE, 
                FALSE,
                FALSE,
                FALSE,
                FALSE,
                FALSE,
                TRUE,
                TRUE,
                TRUE,
                TRUE,
                FALSE,
                FALSE),
    percent = c(TRUE,
                FALSE,
                FALSE,
                TRUE,
                FALSE,
                FALSE,
                FALSE,
                FALSE,
                TRUE,
                TRUE,
                FALSE,
                FALSE),
    footer =  paste0("Data last updated: ")
  )
}
